
development:
  adapter: sqlserver
  database: AdventureWorks
  dataserver: mc2008
  mode: dblib
  username: hr
  password: hr
  pool: 5
  timeout: 5000

test:
  adapter: sqlserver
  database: AdventureWorksTest
  dataserver: mc2008
  mode: dblib
  username: hr
  password: hr
  pool: 5
  timeout: 5000

production:
  adapter: sqlserver
  database: AdventureWorksProduction
  dataserver: 
  mode: dblib
  username: hr
  password: hr
  pool: 5
  timeout: 5000
