
development:
  adapter: sqlserver
  database: AdventureWorks
  host: <%= ENV['ADVENTUREWORKS_HOST'] %>
  username: hr
  password: hr
  pool: 5
  timeout: 5000

test:
  adapter: sqlserver
  database: AdventureWorksTest
  host: <%= ENV['ADVENTUREWORKS_HOST'] %>
  username: hr
  password: hr
  pool: 5
  timeout: 5000


